c.asm cfloats.a -l!spool
c.asm ccdiv.a -l!spool
c.asm ccmod.a -l!spool
c.asm ccmult.a -l!spool
c.asm claddsub.a -l!spool
c.asm clbits.a -l!spool
c.asm clcommon.a -l!spool
c.asm clcompare.a -l!spool
c.asm clconvert.a -l!spool
c.asm cldiv.a -l!spool
c.asm clincdec.a -l!spool
c.asm clmove.a -l!spool
c.asm clmul.a -l!spool
c.asm clnegcompl.a -l!spool
c.asm clshifts.a -l!spool
c.asm cshifts.a -l!spool
c.asm rpterr.a -l!spool
pr comp.maths make.maths!spool
